# Generated by Django 4.2.7 on 2023-11-15 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('RFID', models.CharField(max_length=500)),
                ('StudentId', models.CharField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=500)),
                ('StudentEmail', models.CharField(max_length=500)),
                ('StudentBalance', models.FloatField(default=0)),
                ('StudentStatus', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('TransactionId', models.AutoField(primary_key=True, serialize=False)),
                ('TransactionDate', models.CharField(max_length=500)),
                ('TransactionTime', models.CharField(max_length=500)),
                ('TransactionAmount', models.FloatField(default=0)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='AdminApp.students')),
            ],
        ),
    ]
