# Generated by Django 4.2.7 on 2023-11-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_alter_students_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='TransactionType',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
